FIND_PATH(ASIO_INCLUDE_DIR asio.hpp
  /usr/local/include
  /usr/include
 )

SET(ASIO_FOUND 0)
IF(ASIO_INCLUDE_DIR)
  SET(ASIO_FOUND 1)
ENDIF(ASIO_INCLUDE_DIR)

IF(ASIO_FOUND)
  INCLUDE_DIRECTORIES(${ASIO_INCLUDE_DIR})
ELSE(ASIO_FOUND)
  MESSAGE("PROBLEM: ASIO not found.")
ENDIF(ASIO_FOUND)
